[project]
user_env = []
session_timeout = 3600
user_session_timeout = 1296000
cache = false
persist_user_env = false
mask_user_env = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true
allow_thread_sharing = false

[features.slack]
reaction_on_message_received = false

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
enabled = false
sample_rate = 24000

[features.mcp]
enabled = false
[features.mcp.sse]
enabled = true
[features.mcp.streamable-http]
enabled = true
[features.mcp.stdio]
enabled = true
allowed_executables = ["npx", "uvx"]

[UI]
name = "MediBot"
default_avatar_file_url = "https://images.unsplash.com/photo-1588776814546-5cbf19a3d94a?auto=format&fit=crop&w=1470&q=80"
login_page_image = "https://images.unsplash.com/photo-1588776814546-5cbf19a3d94a?auto=format&fit=crop&w=1470&q=80"
login_page_image_filter = "brightness-50"
default_sidebar_state = "open"
layout = "wide"
cot = "full"
logo_file_url = "https://upload.wikimedia.org/wikipedia/commons/e/e4/Medical_symbol.svg"
alert_style = "modern"
default_theme = "dark"

[meta]
generated_by = "2.9.3"
